services:

  kratos-migrate:
    container_name: kratos-migrate
    image: oryd/kratos:v1.0.0
    volumes:
      - ./ory/kratos:/etc/config/kratos
      - kratos-data:/home/ory
      - kratos-data:/var/lib/sqlite
    command: -c /etc/config/kratos/kratos.yaml migrate sql -e --yes
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - intranet


  kratos:
    container_name: kratos
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
    image: oryd/kratos:v1.0.0
    ports:
      - 127.0.0.1:4433:4433 # public
      - 127.0.0.1:4434:4434 # admin
    volumes:
      - ./ory/kratos:/etc/config/kratos
      - kratos-data:/home/ory
      - kratos-data:/var/lib/sqlite
    command: serve -c /etc/config/kratos/kratos.yaml --dev --watch-courier
    networks:
      - intranet


  postgres:
    container_name: postgres
    image: postgres:15.2
    ports:
      - 127.0.0.1:4455:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d/
    networks:
      - intranet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: "kratos"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"


  mailslurper:
    container_name: mailslurper
    image: oryd/mailslurper:latest-smtps
    ports:
      - 127.0.0.1:4436:4436
      - 127.0.0.1:4437:4437
    networks:
      - intranet


networks:
  intranet:


volumes:
  kratos-data:
  postgres-data:
