[entryPoints]
[entryPoints.web]
address = ":80"
[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
scheme = "https"

[entryPoints.websecure]
address = ":443"

[api]
dashboard = true

[providers.docker]
watch = true
network = "web"

[providers.file]
watch = true
filename = "traefik_dynamic.toml"
